chore: updates to recruitment page and factories
POWERLANE-TEAM/emplo-hrms pull request #39
Opened 2024-09-19 13:44 UTC by C-Ivan-Bandilla

#34

2024-09-19 14:11 UTC, Carl-Tabuso commented
Mention me if this is ready for review.

2024-09-20 05:47 UTC, C-Ivan-Bandilla commented
@Carl-Tabuso

2024-09-23 09:54 UTC, Carl-Tabuso commented on app/Livewire/Auth/Guests/SignUp.php
> +        $this->consent = false;
You can accomplish this using livewire's reset method `$this->reset()` instead of manually assigning empty and boolean values to each property. 

Ref: https://livewire.laravel.com/docs/properties#resetting-properties

2024-09-23 10:19 UTC, Carl-Tabuso commented on database/factories/CompanyDocFactory.php
move this to `PreempRequirements` factory

2024-09-23 10:21 UTC, Carl-Tabuso commented on database/seeders/DatabaseSeeder.php
> +            CompanyDoc::create($document);
backtrack the changes here after moving `predefinedDocuments()` method on `PreempRequirements`

2024-09-23 10:42 UTC, Carl-Tabuso approved these changes
There isn't much to change in this pr. For localization, do you really have to define each english validation messages into their corresponding filipino lang? Is there not a package/library to do this?

2024-09-23 10:44 UTC, Carl-Tabuso commented on resources/views/applicantinfo.blade.php
> +    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
Replace this tailwind cdn

2024-09-23 10:47 UTC, Carl-Tabuso requested changes
There are changes needed in this pr, check the comments. For localization, do you really have to define each english validation messages into their corresponding filipino lang? Is there not a package/library to do this?

2024-09-23 10:53 UTC, Carl-Tabuso commented on resources/views/applicantinfo.blade.php
> +    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
Isn't the head elements defined as a component somewhere? We can use that instead

2024-09-23 11:08 UTC, Carl-Tabuso commented
Since we will be working with quite a lot of forms, I think it's a good idea to create a component out of it. It's kinda hard to understand what's going on with a form element on a file at first glance. 

We can consolidate the assigning of form's input fields and HTTP requests.

Sample file structure inside `resources/views/components`:

forms
├── button.blade.php
├── checkbox.blade.php
├── divider.blade.php
├── error.blade.php
├── field.blade.php
├── form.blade.php
├── input.blade.php
├── label.blade.php
├── select.blade.php
└── _anything else_

button.blade.php
```html
<button {{ $attributes(['class' => 'bg-blue-800 rounded py-2 px-6 font-bold']) }}>{{ $slot }}</button>
```

<hr/>

checkbox.blade.php
```html
@props(['label', 'name'])

@php
    $defaults = [
        'type' => 'checkbox',
        'id' => $name,
        'name' => $name,
        'value' => old($name)
    ];
@endphp

<x-forms.field :$label :$name>
    <div class="rounded-xl bg-white/10 border border-white/10 px-5 py-4 w-full">
        <input {{ $attributes($defaults) }}>
        <span class="pl-1">{{ $label }}</span>
    </div>
</x-forms.field>
```
<hr/>

divider.blade.php
```html
<div>
    <div class="bg-white/10 my-10 h-px w-full"></div>
</div>
```
<hr/>

error.blade.php
```html
@props(['error' => false])

@if ($error)
    <p class="text-sm text-red-500 mt-1">{{ $error }}</p>
@endif
```
<hr/>

form.blade.php
```html
@props(['label', 'name'])

<div>
    @if ($label)
        <x-forms.label :$name :$label />
    @endif

    <div class="mt-1">
        {{ $slot }}

        <x-forms.error :error="$errors->first($name)" />
    </div>
</div>
```
<hr/>

field.blade.php
```html
<form {{ $attributes(["class" => "max-w-2xl mx-auto space-y-6", "method" => "GET"]) }}>
    @if ($attributes->get('method', 'GET') !== 'GET')
        @csrf
        @method($attributes->get('method'))
    @endif

    {{ $slot }}
</form>
```
<hr/>

input.blade.php
```html
@props(['label', 'name'])

@php
    $defaults = [
        'type' => 'text',
        'id' => $name,
        'name' => $name,
        'class' => 'rounded-xl bg-white/10 border border-white/10 px-5 py-4 w-full',
        'value' => old($name)
    ];
@endphp

<x-forms.field :$label :$name>
    <input {{ $attributes($defaults) }}>
</x-forms.field>
```
<hr/>

label.blade.php
```html
@props(['name', 'label'])

<div class="inline-flex items-center gap-x-2">
    <span class="w-2 h-2 bg-white inline-block"></span>
    <label class="font-bold" for="{{ $name }}">{{ $label }}</label>
</div>
```
<hr/>

select.blade.php
```html
@props(['label', 'name'])

@php
    $defaults = [
        'id' => $name,
        'name' => $name,
        'class' => 'rounded-xl bg-white/10 border border-white/10 px-5 py-4 w-full'
    ];
@endphp

<x-forms.field :$label :$name>
    <select {{ $attributes($defaults) }}>
        {{ $slot }}
    </select>
</x-forms.field>
```
<hr/>

Sample Use Case:

```html
<x-layout>
    <x-page-heading>Post a Job</x-page-heading>

    <x-forms.form method="POST" action="/jobs">
        <x-forms.input label="Title" name="title" placeholder="Senior Developer"/>
        <x-forms.input label="Salary" name="salary" placeholder="$90,000 USD"/>
        <x-forms.input label="Location" name="location" placeholder="Winter Park, Florida"/>

        <x-forms.select label="Schedule" name="schedule">
            <option>Part Time</option>
            <option>Full time</option>
        </x-forms.select>

        <x-forms.input label="URL" name="url" placeholder="https://acme.com/jobs/ceo-wanted"/>
        <x-forms.checkbox label="Feature (Costs Extra)" name="featured"/>

        <x-forms.divider/>

        <x-forms.input label="Tags (comma separated)" name="tags" placeholder="Laracasts, video, education"/>

        <x-forms.button>Publish</x-forms.button> 
    </x-forms.form>
</x-layout>
```

This makes the attributes in our forms more consistent.

2024-09-23 13:20 UTC, Carl-Tabuso commented
Shoot! we already have this structure, I didn't notice. Perhaps we can add some of form elements that are still missing. Sorry.

2024-09-23 13:57 UTC, Carl-Tabuso commented
There's this problem serving the CSS for the job listings page. It seemed that the `hiring.css` couldn't be found.


https://github.com/user-attachments/assets/bcdd89e0-7991-4a99-a882-1d9a33ad7349

2024-09-23 14:10 UTC, C-Ivan-Bandilla commented
> Shoot! we already have this structure, I didn't notice. Perhaps we can add some of form elements that are still missing. Sorry.

I also Noticed that the first login page I created used the non components

2024-09-23 14:39 UTC, Carl-Tabuso commented
I need you to also remove the JSON model. It doesn't try to "map" or relate to any tables in our database.

2024-09-23 15:47 UTC, Carl-Tabuso commented
![image](https://github.com/user-attachments/assets/88fed185-4f67-4982-affd-4f64f84c1c41)

Can you add the Sign Up option after the Sign In? And it should also be the one with this class of `nav-link bg-white text-primary`. It's a pattern I've observed with many websites, they tend to put [emphasis on sign up buttons](https://ux.stackexchange.com/questions/101016/why-do-apps-not-emphasise-on-login-buttons-like-they-do-for-sign-up-buttons.) You can treat the Sign In page as any other nav-links.

2024-09-26 05:56 UTC, C-Ivan-Bandilla commented on resources/views/applicantinfo.blade.php
> +    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
> Isn't the head elements defined as a component somewhere? We can use that instead. also remove the tailwind cs

I checked this page
I think this page will be discarded @Cedieziah right?

2024-09-28 11:23 UTC, C-Ivan-Bandilla commented
> ![image](https://private-user-images.githubusercontent.com/162773681/369949696-88fed185-4f67-4982-affd-4f64f84c1c41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MjE0MzQsIm5iZiI6MTcyNzUyMTEzNCwicGF0aCI6Ii8xNjI3NzM2ODEvMzY5OTQ5Njk2LTg4ZmVkMTg1LTRmNjctNDk4Mi1hZmZkLTRmNjRmODRjMWM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQxMDU4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY4NWM3N2E5MjhhMzcxYjgzMDhiNDA2ZTQ4OTg5Y2ZiMjMwYWU1NjA3M2I2M2VkZjE3MmE1NGRkMjg1ZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EWg3ifpod33xPdCdUX5XY3D6j8MqETGN5GI21Xi3dCM)
> 
> Can you add the Sign Up option after the Sign In? And it should also be the one with this class of `nav-link bg-white text-primary`. It's a pattern I've observed with many websites, they tend to put [emphasis on sign up buttons](https://ux.stackexchange.com/questions/101016/why-do-apps-not-emphasise-on-login-buttons-like-they-do-for-sign-up-buttons.) You can treat the Sign In page as any other nav-links.

I made it like this
![image](https://github.com/user-attachments/assets/f0b13dcf-5304-4901-987e-bb073e2328ed)

2024-09-28 11:29 UTC, C-Ivan-Bandilla commented
> There's this problem serving the CSS for the job listings page. It seemed that the `hiring.css` couldn't be found.
> 
>  2024-09-23.21-48-20.mp4

The missing CSS are now included 


https://github.com/user-attachments/assets/238699a6-8da0-455c-8780-0dad59e60dd9

2024-09-28 11:30 UTC, C-Ivan-Bandilla commented
> > Shoot! we already have this structure, I didn't notice. Perhaps we can add some of form elements that are still missing. Sorry.
> 
> I also Noticed that the first login page I created used the non components

I converted them to input components

2024-09-28 11:37 UTC, C-Ivan-Bandilla commented on resources/views/applicantinfo.blade.php
> +    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
I deleted this file, as there is a newer file for this is at **resources\views\apply.blade.php**

@Cedieziah  I modified it in d64fed2 [commit](https://github.com/POWERLANE-TEAM/emplo-hrms/pull/39/commits/d64fed269ca5aec82bacf939a0a0c7bd7cc05d8f#diff-9a845f60fcfb76ba0b803150e94066861b7e010ec131e537f3701cf581c16c8f) and make use of the newer layout file present on other pr #41

2024-09-28 11:38 UTC, C-Ivan-Bandilla commented
> For localization, do you really have to define each english validation messages into their corresponding filipino lang? Is there not a package/library to do this?


Found some like https://www.i18next.com/ but will try to explore some other time

2024-09-28 11:42 UTC, C-Ivan-Bandilla commented on database/factories/CompanyDocFactory.php
c5cd60f  and ther updates to seeder and factory includes the removal of role

2024-09-28 11:44 UTC, C-Ivan-Bandilla commented on app/Livewire/Auth/Guests/SignUp.php
> +        $this->consent = false;
https://github.com/POWERLANE-TEAM/emplo-hrms/blob/3ebe0d1f7acd21086cea3fcf09f220e0fdc54a2f/app/Livewire/Auth/Guests/SignUp.php#L111

Refactored

2024-10-01 15:36 UTC, C-Ivan-Bandilla commented
For Documentation only

Full Query

```
JobVacancy::where('vacancy_count', '>', 1)
            ->where(function ($query) {
                $query->whereDate('application_deadline_at', '>=', Carbon::today())
                    ->orWhereNull('application_deadline_at');
            })
            ->with(['jobDetails', 'jobTitle.jobFamilies', 'jobTitle.specificAreas'])
            ->latest()
            ->get();
```


```
JobVacancy::where('vacancy_count', '>', 1)
            ->where(function ($query) {
                $query->whereDate('application_deadline_at', '>=', Carbon::today())
                    ->orWhereNull('application_deadline_at');
            })
            ->with(['jobDetails, 'jobTitle.specificAreas', 'jobTitle.jobFamilies''])
            ->where(function ($query) use ($search) {
                $query
                    ->WhereHas('jobTitle', function ($query) use ($search) {
                        $query->where('job_title', 'ilike', '%' . $search . '%')
                            ->orWhere('job_desc', 'ilike', '%' . $search . '%');
                    })
                    ->orWhereHas('jobTitle.specificAreas', function ($query) use ($search) {
                        $query->where('area_name', 'ilike', '%' . $search . '%');
                    })
                    ->orWhereHas('jobTitle.jobFamilies', function ($query) use ($search) {
                        $query->where('job_family_name', 'ilike', '%' . $search . '%');
                    });
            })
            ->latest()
            ->get()->map(function ($job_vacancy) use ($search) {

                if ($job_vacancy->jobTitle) {
                    $job_vacancy->jobTitle->job_title = preg_replace_callback('/(' . preg_quote($search, '/') . ')/i', function ($matches) {
                        return "<mark>{$matches[1]}</mark>";
                    }, $job_vacancy->jobTitle->job_title);

                    $job_vacancy->jobTitle->job_desc = preg_replace_callback('/(' . preg_quote($search, '/') . ')/i', function ($matches) {
                        return "<mark>{$matches[1]}</mark>";
                    }, $job_vacancy->jobTitle->job_desc);
                }


                if ($job_vacancy->jobTitle->specificAreas) {
                    foreach ($job_vacancy->jobTitle->specificAreas as $specific_area) {
                        $specific_area->area_name = preg_replace_callback('/(' . preg_quote($search, '/') . ')/i', function ($matches) {
                            return "<mark>{$matches[1]}</mark>";
                        }, $specific_area->area_name);
                    }
                }


                if ($job_vacancy->jobTitle->jobFamilies) {
                    foreach ($job_vacancy->jobTitle->jobFamilies as $job_family) {
                        $job_family->job_family_name = preg_replace_callback('/(' . preg_quote($search, '/') . ')/i', function ($matches) {
                            return "<mark>{$matches[1]}</mark>";
                        }, $job_family->job_family_name);
                    }
                }
            });
```

2024-10-02 09:01 UTC, Carl-Tabuso commented
Can you check #44 before I go about the changes in this PR again? I might miss something if I have to navigate two branches at the same time to make sure the methods in components are up-to-date with the proper changes in the database?

2024-10-02 13:49 UTC, C-Ivan-Bandilla commented
Does PreempRequirement needs morphMap?
![image](https://github.com/user-attachments/assets/6514fa79-e930-4808-8b46-4574fac5b615)

Defining the morphmap for PreempRequirement  removes the error
or 
This also fix the problem (didn't test the polymorph models though)
![image](https://github.com/user-attachments/assets/0237c94c-ca45-4d1d-a94f-97a64391ff9d)

2024-10-02 14:51 UTC, Carl-Tabuso commented
Try fixing the merge conflict then check again if you still run into this issue. `PreempRequirement` is not a morphable model. It solely served the purpose of a checklist for pre-employment requirements.

2024-10-02 15:49 UTC, C-Ivan-Bandilla commented
Since I  stash changes from enforceMorphMap to morphMap

I  get it in JobVacancy too

![image](https://github.com/user-attachments/assets/69d659e2-3e3c-4518-b268-5fa5639142f1)

Signup  and sign in still working

2024-10-03 02:36 UTC, Carl-Tabuso commented
I get the same error too. I don't know why but let's just register PreempRequirement and JobVacancy model to make this work.

2024-10-03 02:49 UTC, Carl-Tabuso commented
i get a 500 status every time i try to sign-up.

![image](https://github.com/user-attachments/assets/95a75e13-a957-4315-8b93-f07f03a2fbd8)

2024-10-03 02:55 UTC, Carl-Tabuso commented on app/Livewire/Auth/Guests/SignUp.php
> +        $new_user_created = $userCreate->create($new_user, true);
![Uploading image.png…]()

2024-10-03 02:57 UTC, Carl-Tabuso commented on app/Livewire/Auth/Guests/SignUp.php
> +        $new_user_created = $userCreate->create($new_user, true);
![image](https://github.com/user-attachments/assets/46fff314-2ee7-427b-9439-d6c445f35d92)

2024-10-03 03:01 UTC, Carl-Tabuso commented on app/Livewire/Auth/Guests/SignUp.php
> +    const ACCOUNT_TYPE = 'applicant';
You can create a backed enum for this. Account type might be used in different parts of the codebase. Will be helpful if we reference it via names/cases instead of string values exclusive to a component.

2024-10-03 03:02 UTC, Carl-Tabuso commented on app/Livewire/Auth/Guests/SignUp.php
> +    const ACCOUNT_STATUS = 'active';
You can remove this and simply reference the enums for account status

2024-10-03 03:08 UTC, Carl-Tabuso commented on app/Http/Controllers/PreEmploymentController.php
idk what's the use case or how this works, sry.

2024-10-03 03:21 UTC, C-Ivan-Bandilla commented
> i get a 500 status every time i try to sign-up.
> 
> ![image](https://private-user-images.githubusercontent.com/162773681/373097831-95a75e13-a957-4315-8b93-f07f03a2fbd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjUwMTMsIm5iZiI6MTcyNzkyNDcxMywicGF0aCI6Ii8xNjI3NzM2ODEvMzczMDk3ODMxLTk1YTc1ZTEzLWE5NTctNDMxNS04YjkzLWYwN2YwM2EyZmJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwMzA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGE2NzU0YzY0ZmYzZWFjMWNhNWRlODhkMTBkNTJjYWQ5NGEzNzg4MTUwOGVhMGFjYWYwMTBjMTI4YjcwY2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RjUoiz23aeHyQp6p6FoF-xDPjC8PMOu-2ZWkTHLZF9Q)

Ahh this is an extension in ini

I enabled this a long time ago on my end when using faker

will update pr description

2024-10-03 03:23 UTC, Carl-Tabuso commented on resources/views/livewire/employee/pre-employment-doc.blade.php
> +    <form action="" wire:model="document_id" name="{{ $doc_id }}">
`wire:model="document_id"` is not bound by any property in its corresponding component thus throwing a warning on the console.

2024-10-03 03:38 UTC, Carl-Tabuso commented on database/factories/ApplicationStatusFactory.php
> +            ['application_status_name' => 'REJECTED', 'application_status_desc' => 'Rejected application'],
this can be a backed enum since they're constants.

2024-10-03 03:43 UTC, Carl-Tabuso commented on database/factories/PreempRequirementFactory.php
this file can be deleted. We preemptively defined what the preemp_requirements table should hold. We can just seed the database from PreempRequirementSeeder.

2024-10-03 03:45 UTC, Carl-Tabuso commented on database/seeders/DatabaseSeeder.php
would be nice if we can move the loops and other conditionals in factories and seeders. This'll do for now.

2024-10-03 03:59 UTC, Carl-Tabuso commented on resources/views/components/layout/livewire-global-listener.blade.php
> +    document.addEventListener('livewire:init', () => {
if you want, you may remove the document.addEventListener and replace it by @script directive instead. https://livewire.laravel.com/docs/javascript#executing-scripts

2024-10-03 04:12 UTC, Carl-Tabuso commented on resources/views/components/form/checkbox-terms-condition.blade.php
are there any reasons to use unescaped HTML `{{ !! $attribute !! }}`  ?

2024-10-03 04:13 UTC, Carl-Tabuso commented on resources/views/apply.blade.php
![image](https://github.com/user-attachments/assets/2d67176e-b160-4771-bda3-47e8ea1b4899)

2024-10-03 07:10 UTC, Carl-Tabuso commented
I checked the livewire docs but it wasn't specified in there that `$this->reset()` actually does reset every properties. I just noticed this in SignUp component. You're not passing the properties as parameters.

```php
class SignUp extends Component
{
    // properties

    public function store(CreateNewUser $userCreate)
    {
        // some codes

        $this->reset();
    }

}
```

2024-10-03 08:27 UTC, C-Ivan-Bandilla commented
> I checked the livewire docs but it wasn't specified in there that `$this->reset()` actually does reset every properties. I just noticed this in SignUp component. You're not passing the properties as parameters.
> 
> ```
> class SignUp extends Component
> {
>     // properties
> 
>     public function store(CreateNewUser $userCreate)
>     {
>         // some codes
> 
>         $this->reset();
>     }
> 
> }
> ```

![image](https://github.com/user-attachments/assets/f8456a04-2464-4049-a2ac-4ee7b4775849)
it actually resets all if no property specified

will upload the proof later

but I can just specify it explicitly

2024-10-03 13:24 UTC, Carl-Tabuso approved these changes
I think this'll do for now. I just noticed this when I try to directly access the /apply URI.

![image](https://github.com/user-attachments/assets/509ac7c7-0d9c-40cc-9155-bfce06e02519)

2024-10-03 14:45 UTC, merged